/*
DB name: mapaestrategico
*/

CREATE TABLE IF NOT EXISTS `PERSPECTIVAS` (
  `idPERSPECTIVA` INT NOT NULL AUTO_INCREMENT,
  `TIPO_PERSP` VARCHAR(20) NULL,
  `SITUACAO_PERSP` VARCHAR(10) NULL,
  `DESCRICAO_PERSP` VARCHAR(50) NULL,
  PRIMARY KEY (`idPERSPECTIVA`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `GRUPOS` (
  `idGRUPO` INT NOT NULL AUTO_INCREMENT,
  `CATEGORIA` VARCHAR(100) NULL,
  `PERSPECTIVAS_idPERSPECTIVA` INT NOT NULL,
  `SITUACAO_GR` VARCHAR(10) NULL,
  PRIMARY KEY (`idGRUPO`),
  INDEX `fk_GRUPOS_PERSPECTIVAS_idx` (`PERSPECTIVAS_idPERSPECTIVA` ASC),
  CONSTRAINT `fk_GRUPOS_PERSPECTIVAS`
    FOREIGN KEY (`PERSPECTIVAS_idPERSPECTIVA`)
    REFERENCES `mydb`.`PERSPECTIVAS` (`idPERSPECTIVA`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDBB

CREATE TABLE IF NOT EXISTS `OBJETIVOS` (
  `idOBJETIVO` INT NOT NULL AUTO_INCREMENT,
  `DESCRICAO_OBJ` VARCHAR(100) NULL,
  `GRUPOS_idGRUPO` INT NOT NULL,
  `SITUACAO_OBJ` VARCHAR(10) NULL,
  PRIMARY KEY (`idOBJETIVO`),
  INDEX `fk_OBJETIVOS_GRUPOS1_idx` (`GRUPOS_idGRUPO` ASC),
  CONSTRAINT `fk_OBJETIVOS_GRUPOS1`
    FOREIGN KEY (`GRUPOS_idGRUPO`)
    REFERENCES `GRUPOS` (`idGRUPO`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `PROJETOS` (
  `idPROJETO` INT NOT NULL AUTO_INCREMENT,
  `NOME_PROJ` VARCHAR(100) NULL,
  `DATA_INI` DATE NULL,
  `DATA_FIM` DATE NULL,
  `GERENTE` VARCHAR(80) NULL,
  `OBJETIVOS_idOBJETIVO` INT NOT NULL,
  `SITUACAO_PROJ` VARCHAR(10) NULL,
  PRIMARY KEY (`idPROJETO`),
  INDEX `fk_PROJETO_OBJETIVOS1_idx` (`OBJETIVOS_idOBJETIVO` ASC),
  CONSTRAINT `fk_PROJETO_OBJETIVOS1`
    FOREIGN KEY (`OBJETIVOS_idOBJETIVO`)
    REFERENCES `OBJETIVOS` (`idOBJETIVO`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB


CREATE TABLE IF NOT EXISTS `INDICADORES` (
  `idINDICADORES` INT NOT NULL AUTO_INCREMENT,
  `OBJETIVOS_idOBJETIVO` INT NOT NULL,
  `SITUACAO_IND` VARCHAR(45) NULL,
  `CONFIG_IND` VARCHAR(600) NULL,
  `DESCRICAO_IND` VARCHAR(45) NULL,
  PRIMARY KEY (`idINDICADORES`),
  INDEX `fk_INDICADORES_OBJETIVOS1_idx` (`OBJETIVOS_idOBJETIVO` ASC),
  CONSTRAINT `fk_INDICADORES_OBJETIVOS1`
    FOREIGN KEY (`OBJETIVOS_idOBJETIVO`)
    REFERENCES `OBJETIVOS` (`idOBJETIVO`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
   

CREATE TABLE IF NOT EXISTS `METAS` (
  `INDICADORES_idINDICADORES` INT NOT NULL AUTO_INCREMENT,
  `idMETAS` INT NOT NULL,
  `SITUACAO_MET` VARCHAR(10) NULL,
  `DESCRICAO_MET` VARCHAR(100) NULL,
  `UNIDADE` VARCHAR(15) NULL,
  `VERMELHO_INI` INT NULL,
  `VERMELHO_LIM` INT NULL,
  `AMARELO_INI` INT NULL,
  `AMARELO_LIM` INT NULL,
  `VERDE` INT NULL,
  INDEX `fk_METAS_INDICADORES1_idx` (`INDICADORES_idINDICADORES` ASC),
  PRIMARY KEY (`idMETAS`),
  CONSTRAINT `fk_METAS_INDICADORES1`
    FOREIGN KEY (`INDICADORES_idINDICADORES`)
    REFERENCES `mydb`.`INDICADORES` (`idINDICADORES`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `MAPAS` (
  `idME` INT NOT NULL AUTO_INCREMENT,
  `OBJETIVOS_idOBJETIVO` INT NOT NULL,
  `SITUACAO_ME` VARCHAR(10) NULL,
  `MISSAO` VARCHAR(400) NULL,
  `VISAO` VARCHAR(400) NULL,
  `ANO` INT NULL,
  INDEX `fk_MAPAESTRATÉGICO_OBJETIVOS1_idx` (`OBJETIVOS_idOBJETIVO` ASC),
  PRIMARY KEY (`idME`),
  CONSTRAINT `fk_MAPAESTRATÉGICO_OBJETIVOS1`
    FOREIGN KEY (`OBJETIVOS_idOBJETIVO`)
    REFERENCES `OBJETIVOS` (`idOBJETIVO`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
  
CREATE TABLE IF NOT EXISTS `ITENS` (
  `idITENS` INT NOT NULL AUTO_INCREMENT,
  `MAPAESTRATEGICO_idME` INT NOT NULL,
  `PERSPECTIVAS_idPERSPECTIVA` INT NULL,
  `GRUPO_idGRUPO` INT NULL,
  `OBJETIVOS_idOBJETIVO` INT NULL,
  `INDICADORES_idINDICADOR` INT NULL,
  PRIMARY KEY (`idITENS`),
  INDEX `fk_INTENS_ME_MAPAESTRATEGICO1_idx` (`MAPAESTRATEGICO_idME` ASC),
  CONSTRAINT `fk_INTENS_ME_MAPAESTRATEGICO1`
    FOREIGN KEY (`MAPAESTRATEGICO_idME`)
    REFERENCES `MAPAS` (`idME`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB


    